import os
import sys
import subprocess
import shutil

def run_test():
    print("=" * 60)
    print("Meltpool PostProcessing Environment Test")
    print("=" * 60)
    
    # 路径配置
    script_path = "/home/cgh/LaserbeamFoam/applications/scripts/postProcessing/characterise_meltpool.py"
    test_dir = os.path.dirname(os.path.abspath(__file__))
    
    # 检查 OpenFOAM 必要文件
    required_dirs = ["system", "constant"]
    # 0.0007 might be named differently or copy might have failed.
    # Let's check for ANY numerical directory or just warn.
    
    for d in required_dirs:
        if not os.path.exists(os.path.join(test_dir, d)):
             print(f"FAILED: Required OpenFOAM directory '{d}' not found in test folder.")
             print(f"Current contents of {test_dir}: {os.listdir(test_dir)}")
             return

    # Check for time directory
    time_dirs = [d for d in os.listdir(test_dir) if d.replace('.','').isdigit() and os.path.isdir(os.path.join(test_dir, d))]
    if not time_dirs:
         print("WARNING: No time directory (e.g. 0.0007) found. Extraction might fail.")
         print(f"Current contents: {os.listdir(test_dir)}")
    else:
         print(f"Found time directories: {time_dirs}")

    # Check meltpool.csv (source for verification if extraction fails, or destination)
    meltpool_csv = os.path.join(test_dir, "meltpool.csv")
    if os.path.exists(meltpool_csv):
        print(f"Found existing meltpool.csv (will be overwritten if extraction succeeds)")
    else:
        print("No meltpool.csv found. It must be generated by extraction.")
             
    print(f"Script to test: {script_path}")
    print(f"Script to test: {script_path}")
    print("Running FULL post-processing script (including ParaView extraction)...")
    print("-" * 60)

    # 设置环境变量：确保不跳过 pvpython
    env = os.environ.copy()
    if "SKIP_PVPYTHON" in env:
        del env["SKIP_PVPYTHON"]
    
    # 尝试设置 OF_LOCATION 如果它是一个常用路径，或者依赖用户环境
    # 这里我们假设用户环境已经加载了 OpenFOAM，或者脚本通过 source 加载
    
    try:
        # 运行脚本
        subprocess.run([sys.executable, script_path], cwd=test_dir, env=env, check=True)
        print("-" * 60)
        
        # 验证输出
        if os.path.exists(os.path.join(test_dir, "meltpool.csv")):
             print("[PASS] extraction ran and meltpool.csv exists")
        
        output_files = ["cross_sections_statistics.csv", "metrics_summary.csv"]
        all_passed = True
        
        for f in output_files:
            f_path = os.path.join(test_dir, f)
            if os.path.exists(f_path) and os.path.getsize(f_path) > 0:
                print(f"[PASS] generated {f}")
            else:
                print(f"[FAIL] {f} missing or empty")
                all_passed = False

        if all_passed:
            # Compare with expected results
            expected_summary_path = os.path.join(test_dir, "expected_metrics_summary.csv")
            current_summary_path = os.path.join(test_dir, "metrics_summary.csv")
            
            if os.path.exists(expected_summary_path):
                print("-" * 60)
                print("Verifying results against baseline...")
                try:
                    import pandas as pd
                    # Load locally to avoid dependency issues if pandas not available (though it is used in script)
                    # But since the script ran, pandas is available.
                    
                    df_exp = pd.read_csv(expected_summary_path)
                    df_curr = pd.read_csv(current_summary_path)
                    
                    # Compare columns
                    cols_to_check = ["width_mean_um", "height_mean_um", "depth_mean_um"]
                    mismatch = False
                    
                    for col in cols_to_check:
                        val_exp = df_exp[col].iloc[0]
                        val_curr = df_curr[col].iloc[0]
                        # Use a small tolerance for floating point differences across machines/runs
                        # However, since this is deterministic post-processing on same machine, it should be very close.
                        diff = abs(val_exp - val_curr)
                        if diff > 1e-4:
                            print(f"[FAIL] {col} mismatch! Expected: {val_exp:.6f}, Got: {val_curr:.6f}, Diff: {diff:.6e}")
                            mismatch = True
                        else:
                            print(f"[OK] {col} matches ({val_curr:.4f})")
                            
                    if mismatch:
                        print("FAILURE: Results do not match the expected baseline.")
                        all_passed = False
                    else:
                        print("SUCCESS: Results match the expected baseline exactly.")
                        
                except Exception as e:
                    print(f"WARNING: Could not verify against baseline: {e}")
            else:
                print("WARNING: No baseline file found (expected_metrics_summary.csv). Skipping comparison.")

        if all_passed:
            print("=" * 60)
            print("SUCCESS: Environment check passed!")
            print("The post-processing script logic is working correctly with your current python environment.")
            print("=" * 60)
        else:
            print("=" * 60)
            print("FAILURE: Output files were not generated correctly.")
            print("Please check the error messages above.")
            print("=" * 60)
            
    except subprocess.CalledProcessError as e:
        print(f"\nError running script: {e}")
        print("FAILURE: The script crashed during execution.")
    except Exception as e:
        print(f"\nUnexpected error: {e}")

if __name__ == "__main__":
    run_test()
